### ISSUE TITLE
ccdb command print errors to stderr

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/ccdb#10]
For debugging purposes, it would be useful if the ccdb CLI program printed errors to stderr instead of stdout.  In some batch jobs, I was getting errors like the following which were showing up in stdout, and it would be easier to track them down if they showed up in stderr:

CCDB provider unable to connect to sqlite:///home/gxproj3/calib_challenge/ccdb.sqlite. Aborting command. Exception details: (OperationalError) unable to open database file None None

**Comment by DraTeots** [comment]
Have to look into that. CCDB utilizes standard python logging mechanism. Probably it should just be configured correctly to fix the issue.
