### ISSUE TITLE
mysqldump converts times to UTC by default

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/ccdb#100]
The creation time of CCDB entries is shifted by 4h when comparing the mysql database and an sqlite file. Here is an example from the mysql database:
```
ccdb ls FDC/package1/wire_timing_offsets
/FDC/package1/wire_timing_offsets
(ID)     (created)              (user)           (variation)     (run range)      (comments)
 651588  2024-10-04 14-57-10    aaustreg         default         121207-121207   
```
And the same example from the sqlite file in `/work/halld2/home/gxproj5/sqlite/ccdb_monitoring_launch.sqlite`, create by this command:
```
mysqldump -u ccdb_user -h hallddb.jlab.org ccdb > dump.mysql.sql
$CCDB_HOME/scripts/mysql2sqlite/mysql2sqlite dump.mysql.sql | sqlite3 ccdb.sqlite
```
```
ccdb ls FDC/package1/wire_timing_offsets
/FDC/package1/wire_timing_offsets
(ID)     (created)              (user)           (variation)     (run range)      (comments)
 651588  2024-10-04 18-57-10    aaustreg         default         121207-121207
```

**Comment by sdobbs** [comment]
FWIW, I think it can be resolved by adding the `--skip-tz-utc` flag to the `mysqldump` command.  In that case, the documentation should be updated - not sure when this issue was introduced, though.

**Comment by DraTeots** [comment]
Added to the documentation. Please feel free to edit it more if needed

https://github.com/JeffersonLab/ccdb/wiki/Develop-CCDB#convert-mysql-to-sqlite
