### ISSUE TITLE
Problems using low-level API to write tables to SQLite files

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/ccdb#16]
I've run into a possible problem using the python low-level API to add assignments to an SQLite file.  This code had worked up until about a month ago, for what it's worth.

I've attached a python script that reproduces the problem, along with the output that it produces.  

I've been able to reproduce the bug using several SQLite files on various locations in the JLab CUE.  It works fine with the MySQL master DB.  

[example.zip](https://github.com/JeffersonLab/ccdb/files/86462/example.zip)

**Comment by DraTeots** [comment]
It looks working... No errors. 

I downloaded SQLite db from:  
https://halldweb.jlab.org/dist/ccdb.sqlite

added it to connection:

``` python
 ccdb_connect_str = "sqlite:///" + os.path.join("ccdb.sqlite")
```

And put these lines to the end to check the script is working:

``` python
    table = provider.get_type_table("/BCAL/ADC_timing_offsets")
    for cs in table.constant_sets:
        print cs.assignment, cs.assignment.created, cs.assignment.variation.name, cs.assignment.run_range.min, cs.data_list
```

And see how assignments are created using this script:

```
<Assignment '7915'> 2016-01-12 22:11:21.426000 calib 3180 [u'0.0', u'0.0', ... u'0.0']
<Assignment '7916'> 2016-01-12 22:12:55.768000 calib 3180 [u'0.0', u'0.0', ..., u'0.0']
```

**Comment by sdobbs** [comment]
That's interesting - I just tried it again, using the SQLite file you mention, and got the same maximum recursion depth reached error.  
I've put the SQLite file I'm using in /u/scratch/gxproj3/ccdb.sqlite, if you want to try it.

**Comment by DraTeots** [comment]
Could you post an error output?

**Comment by sdobbs** [comment]
It's pretty long, so I included it as the "log" file in the zip file.

**Comment by DraTeots** [comment]
Sorry! I didn't figure it out.

**Comment by abarnes12** [comment]
@DraTeots, @sdobbs 

Since this hasn't been marked solved, I'd like to add to this issue.

I recently tried modifying the translation table with an XML file, as instructed on the wiki https://halldweb.jlab.org/wiki/index.php/Translation_Table. While trying to use the python script to push the XML into the CCDB I get the same error as Sean when I do it on the ifarm. However, doing the same action at UConn didn't result in the error.

After some digging I noticed that UConn uses CCDB 1.05 whereas the ifarm is using 1.06. I tried comparing the two versions but I haven't noticed anything that would create this issue.

**Comment by sparksn** [comment]
I believe this has been fixed on the master branch by PR #28

**Comment by abarnes12** [comment]
That's strange, I only managed to get it to work using 1.05. When I tried 1.06.01 on the ifarm I had the same runtime error as PR #28. Have you managed to update the translation table with 1.06.01?

**Comment by sparksn** [comment]
`ccdb-1.06.01` did not work for me either: The bug was introduced in that release.
I used `1.06.00` to update the translation table.

I know it is a bit late now, sorry Alex, but I will send an email to the offline list about this issue now.

**Comment by DraTeots** [comment]
At least works win v2.00
