### ISSUE TITLE
Problems with SQLite files on the ifarm?

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/ccdb#26]
I've been working on some calibrations on the ifarm machine, using SQLite CCDB files, but when I make changes to these files, it looks like they are modified, but ccdb log show no changes.

An example file is here:  /u/scratch/sdobbs/ccdb.sqlite
I changed the /PHOTON_BEAM/RF/time_offset table, but this change doesn't show.

**Comment by DraTeots** [comment]
Logs are off for SQLite file in assumption that main logging reason is to determine who did what and it is not relevant for SQLite

**Comment by sdobbs** [comment]
Ah, okay, thanks for the reminder.  I find it useful for debugging, but it's not really critical.
