### ISSUE TITLE
password prompt when adding variation

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#3]
This one came in over email from Sean Dobbs (@sdobbs):

When adding the variation for the 2016 simulations on the ifarm, it asked me for a password for some reason [terminal capture at the end of the email].  I put in "ccdb" and that worked fine, but I'm not sure if it's supposed to do that.

ifarm1102> ccdb mkvar mc_sim1 -p mc 
Variation mc_sim1 created
Enter MySql password: 
Password:

**Comment by DraTeots** [comment]
I'm not sure it's supposed to do that too. There is no such question "Enter MySql password" in CCDB code. Could it be mysql settings, to ask password if no password is given? I'll check, what is happening.

**Comment by sdobbs** [comment]
This happened again... apparently it only happens when I try and make a variation that has a parent that is not default.

**Comment by DraTeots** [comment]
I have updated SQLAlchemy. Could you check if the problem gone?

**Comment by sdobbs** [comment]
I've tested it with the latest version of the master branch, and still see the problem.  I am also still seeing the problem from issue #5 using the command line client - haven't checked with my other python scripts.

**Comment by DraTeots** [comment]
Fixed in 6f42253360970a74604d84c80ba63e110631ddbe
Still needs some tests before closing the ticket

**Comment by sdobbs** [comment]
#3 and #5 are fixed for me with the latest release.

**Comment by DraTeots** [comment]
Thank you!
