### ISSUE TITLE
[Java] Any Java examples available?

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/ccdb#50]
Are there Java examples available anywhere showing how to use this API?

It would be especially helpful to see simple examples of adding, selecting, modifying and deleting data sets from the DB.

Thanks.

**Comment by JeremyMcCormick** [comment]
I now see there are examples in `java/src/javaExamples`.

**Comment by DraTeots** [comment]
Please, feal free to ask if you need more examples or something is wrong with existing ones
