### ISSUE TITLE
Error when creating directory in ccdb command line tool

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/ccdb#51]
When I execute this in the command shell

```
/> mkdir /test2
```

I get this error with a blank exception message

```
Failed to create directory. Exception message:
```

I am using a copy of the sqlite data file provided in the ccdb git project e.g.

```
ccdb -c sqlite:///$PWD/src/main/sql/ccdb.sqlite -i
```

Several other commands such as `ls`, etc. seem to work fine.

Am I able to create new tables via this interface or no?

Thanks.

**Comment by markito3** [comment]
I was able to create directories just now:

> setenv CCDB_CONNECTION sqlite:////local/scratch/ccdb_make_dir/ccdb.sqlite
> ccdb -i

+--------------------------+
  CCDB shell v.1.07.00
+--------------------------+
       
Interactive mode
print help to get help
print quit or q to exit
print !<command> to execute shell command

Login as   : 'marki'
Connect to : 'sqlite:////local/scratch/ccdb_make_dir/ccdb.sqlite'
Variation  : 'default'
Deflt. run : '0'
/> ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
/> mkdir test2
Directory test2 created
/> mkdir /test3
Directory test3 created
/> ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
test2
test3
/> cd test3
/test3> ls
Can't find the directory or tables
/test3> mkdir a
Directory a created
/test3> mkdir b
Directory b created
/test3> mkdir c
Directory c created
/test3> ls
a
b
c
/test3> cd ..
/> ls test3   
a
b
c

**Comment by markito3** [comment]
I also tried with the "-c" form of specifying the sqlite file:

> unsetenv CCDB_CONNECTION 
> ccdb -c sqlite:////local/scratch/ccdb_make_dir/ccdb.sqlite -i

+--------------------------+
  CCDB shell v.1.07.00
+--------------------------+
       
Interactive mode
print help to get help
print quit or q to exit
print !<command> to execute shell command

Login as   : 'marki'
Connect to : 'sqlite:////local/scratch/ccdb_make_dir/ccdb.sqlite'
Variation  : 'default'
Deflt. run : '0'
/> ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
test2
test3
/> mkdir test4
Directory test4 created
/> mkdir /test5
Directory test5 created

**Comment by markito3** [comment]
I also tried it with the sqlite file from the git repository. Worked for me with that as well. There is a problem with sqlite files on Lustre systems. That is not the case for you, is it?

**Comment by DraTeots** [comment]
Also, which CCDB version do you use and what is the database source?

**Comment by JeremyMcCormick** [comment]
I am using the ccdb master, and the db source is a copy of `ccdb/sql/ccdb.sqlite`.

I am assuming that the issue has to do with making a dir as the 'anonymous' user, but I can't tell because the exception message is empty.

I do not see how to actually change my user name when using the command line tool using SQLite.

@markito3 I see that it somehow knows your username when you use the tool without you giving this info explicitly.

```
Login as : 'marki'
```

How would I get it to use a non-anonymous user when I connect to a SQLite db?

Thanks.

**Comment by JeremyMcCormick** [comment]
I managed to figure this out.  It was not happy with using the 'anonymous' account for creating a dir.

I set in my shell a user that I created:

```
export CCDB_USER=jerm
```

Now it works!

BTW, I didn't see the `CCDB_USER` var mentioned anywhere in the docs.  Is this explained someplace?  (I would have expected to see it in the CLI doc.)

**Comment by markito3** [comment]
At some point we grabbed the username from the $USER environment variable. Perhaps that is no longer the case.

I notice that at least one of our "standard" environment setting scripts tries to set CCDB_USER explicitly:

if (! $?CCDB_USER) then
    if ($?USER) then
        setenv CCDB_USER $USER
    endif
endif

appears in our C-shell script.
