### ISSUE TITLE
Questions about data model

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/ccdb#53]
Just a few questions...

Is it by design that assignments to a table must always have a fixed number of rows?  For instance, I have a bad channel set that has a variable number of rows.  Would it be better to model this so that every channel has a value with a boolean value so that every dataset has the same number of rows?

Can I assign multiple independent run ranges to the same set of calibration data? Or should I instead duplicate the data for the new run range?

Thanks.

**Comment by markito3** [comment]
Variable length tables are not supported at present. Others in similar situations have stored values in a single variable length string, and then parsed the result themselves.

The database design supports independent run ranges using the same constant sets. I am not sure whether the current implementation supports that however. If not we need to add that capability. With this mechanism, you can check the equality of constants just by the equality of the constant set ID and not have to check constant by constant.
