### ISSUE TITLE
Lustre issues?

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/ccdb#54]
I'd forgotten, with the latest releases, are we moving towards Lustre compatibility?  

I'd had some questions sent my way recently in which there were problems with SQLite DBs, which may be due to a filesystem problem, but the usual errors were not thrown.  If the diagnosis is correct, I'll open another issue, but wanted to check on this point first.

**Comment by markito3** [comment]
I've not heard of any change on the Lustre front.

**Comment by sdobbs** [comment]
Nevermind, this ended up as a different problem.
