### ISSUE TITLE
Use of cat --id

### ISSUE THREAD

**Issue by forcar** [JeffersonLab/ccdb#55]
Using cat --id command corrupts the command line interface ("No row was found for one()").  

![screen shot 2017-09-22 at 2 09 38 pm](https://user-images.githubusercontent.com/10797791/30758312-e0fec4ba-9f9f-11e7-93ea-42c11d1bdc4b.png)

**Comment by markito3** [comment]
I was able to reproduce this using the Hall D CCDB.
<pre>
/test/test_vars> cat test_table:4206
+--------------------------------------+
| x          | y          | z          |
| double     | double     | double     |
+--------------------------------------+
| 10         | 2          | 30         |
| 40         | 5          | 60         |
+--------------------------------------+
/test/test_vars> cat --id 7546 test_table
+--------------------------------------+
| x          | y          | z          |
| double     | double     | double     |
+--------------------------------------+
| 1.         | 2.         | 3.         |
| 2.         | 3.         | 4.         |
+--------------------------------------+
/test/test_vars> cat test_table:4206
No row was found for one()
</pre>

**Comment by DraTeots** [comment]
Fixed in CCDB v2, tested
