### ISSUE TITLE
Auto disconnect-from-server feature not implemented or not working

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#62]
The CCDB is supposed to close the connection to the MariaDB server after the connection goes unused for some amount of time. After that if a request for constants comes in it is supposed to reconnect. Am now seeing connections from the farm lasting up to seven hours. Either the feature is not there in the version we are running, or it is not implemented correctly, or it is not working, or the time-out is set to a value greater than 7 hours. I think 30 minutes would be about right, maybe less. See this [snapshot of hallddb from the processlist table](https://github.com/JeffersonLab/ccdb/files/2971896/issue.txt).

**Comment by DraTeots** [comment]
CCDB C++ API `Calibration` class implements 

[GetLastActivityTime()](https://github.com/JeffersonLab/ccdb/blob/v2-main/cpp/src/CCDB/Calibration.h#L246)

This function could be used to go over existing calibration classes, check how long they are not active and close the connection (see [Disconnect](https://github.com/JeffersonLab/ccdb/blob/v2-main/cpp/src/CCDB/Calibration.h#L74)). The connection is then reopened automatically if `GetCalib` is called. It probably has been never implemented on JANA2 side.

**Comment by DraTeots** [comment]
More info here

https://github.com/JeffersonLab/ccdb/wiki/C---Overview#managing-mysqlcalibration-manually
