### ISSUE TITLE
Cannot write to ccdb sqlite, no error message

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/ccdb#63]
It would be great if ccdb would give an error message when the user tries to correctly create or add to a table and ccdb cannot do this due to ???, idk what the root of the problem is, but it can't. 

When I add data to a ccdb sqlite file in my home dir on ifarm, I see the write confirmation message, which looks like table_name:run_number:variation:date.   When I do this on the CMU machines, ccdb returns nothing, and does not write the data. 

I'm not sure why I cannot write into the ccdb sqlite file at CMU - originally I thought it was because one of the disks was NFS, but after copying it onto /tmp I still couldn't write to ccdb.

One of the IU students recently asked the software help list about this same issue.  It would be good if ccdb returned an error message, so that the user does not have to remember that they should see the confirmation message instead.

**Comment by sdobbs** [comment]
I wonder if this is related to a problem I had recently - I wasn't able to add constants from a particular machine, and then realized I didn't have my CCDB_USER environment variable set properly.  The CLI shouldn't silently fail if this is not set but is required.

**Comment by DraTeots** [comment]
> The CLI shouldn't silently fail if this is not set but is required
Indeed!

Looking into this. 

P.S. Previously it silently failed because of sqlite library. It was investigated by Mark Ito

**Comment by DraTeots** [comment]
In 2.0 I have reworked how exception got handled so it shouldn't be silent now. I guess this issue is closed as it is pretty old now
