### ISSUE TITLE
Unit test failure, CCDB 2.00

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#77]
- On branch 2.00 (commit 8b5a92d27)
- Running CCDB_tests, with on-board sqlite file, gives [CCDB_tests.log](https://github.com/JeffersonLab/ccdb/files/6245362/CCDB_tests.log)
- Running again with a CCDB2-type database, gives [CCDB_tests_2.log](https://github.com/JeffersonLab/ccdb/files/6245386/CCDB_tests_2.log). No change.
  - Conversion done at on lorentz.jlab.org, first from ccdb to ccdb2 on the mysql server, then conversion of ccdb2 from mysql to sqlite. Transferred to Fedora 33 machine to run the test.

**Comment by DraTeots** [comment]
Fixed
