### ISSUE TITLE
ccdb -i no go, ccdb 1.06.07, Fedora 33

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#79]
- The following is **not** a problem with RHEL7 at the lab.
- Running on Fedora 33
  - default python is 3.9.2
- Fresh clone of ccdb
- Checkout v1.06.07
- source environment.bash
- ccdb -i complains about colorama:

```
$ ccdb -i
Traceback (most recent call last):
  File "/scratch/ccdb_test2/ccdb/bin/ccdb", line 5, in <module>
    ccdb.init_ccdb_console()
  File "/scratch/ccdb_test2/ccdb/python/ccdb/__init__.py", line 48, in init_ccdb_console
    import cmd.colorama
ModuleNotFoundError: No module named 'cmd.colorama'; 'cmd' is not a package
```

**Comment by DraTeots** [comment]
ccdb 1.06 will not work with python 3

**Comment by DraTeots** [comment]
In order to try it with python 2

```bash
python2 $CCDB_HOME/python/ccdbcmd.py -i
```

The colorama is located here

```
python/ccdb/cmd/colorama
```

And import cmd.colorama should be changed to 

```python
import .cmd.colorama  # make it relative
```

But the whole issue tells that it will fail on the next python2-3 issues

**Comment by DraTeots** [comment]
Everything is tested to be working for v2.00
