### ISSUE TITLE
compilation error with version 2.00-test

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/ccdb#95]
In file included from /usr/include/signal.h:328,
                 from /home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/catch.hpp:6117,
                 from /home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/tests.cc:13:
/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/catch.hpp:8743:54: **error: call to non-'constexpr' function 'long int sysconf(int)'**
 8743 | constexpr static std::size_t **sigStackSize** = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                      ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/catch.hpp:6117,
                 from /home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/tests.cc:13:
/usr/include/unistd.h:640:17: note: 'long int sysconf(int)' declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/tests.cc:13:
/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/src/Tests/catch.hpp:8802:41: error: **size of array 'altStackMem' is not an integral constant-expression**
 8802 | char FatalConditionHandler::altStackMem[**sigStackSize**] = {};
      |                                         ^~~~~~~~~~~~
make[4]: *** [src/Tests/CMakeFiles/CCDB_tests.dir/build.make:79: src/Tests/CMakeFiles/CCDB_tests.dir/tests.cc.o] Error 1
make[4]: Leaving directory '/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/build'
make[3]: *** [CMakeFiles/Makefile2:145: src/Tests/CMakeFiles/CCDB_tests.dir/all] Error 2
make[3]: Leaving directory '/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/build'
make[2]: *** [Makefile:94: all] Error 2
make[2]: Leaving directory '/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb/ccdb_2.00-test/cpp/build'
make[1]: *** [/home/zihlmann/SOFTWARE/ALMA9/gluex_top/build_scripts/Makefile_ccdb:81: ccdb_2.00-test/.make_done] Error 2
make[1]: Leaving directory '/home/zihlmann/SOFTWARE/ALMA9/gluex_top/ccdb'
make: *** [/home/zihlmann/SOFTWARE/ALMA9/gluex_top/build_scripts/Makefile_all:173: ccdb_make] Error 2
pass 1 failed, exiting

**Comment by DraTeots** [comment]
2.00-test is severely outdated. Could you try using 'v2-main' branch?

`v2-main` is currently the main branch of the project. There were no tags recently and I will create one after fixing one problem and making `ccdb db upgrade` command. So for now please use v2-main it should be in betta-stable state. 

`v1-main` is supposed to be used to add any fixes and patches to CCDB v1 if needed. But it hasn't been needed yet. Legacy.
