### ISSUE TITLE
compilation error with v2-main

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/ccdb#96]
some of the test rutines in ccdb/cpp/src/tests use a capital letter "T" in the include string
rather than a lower case letter "t"

it should be "#include "tests/tests.h" ect. NOT "#include "Tests/test.h" ect. 

ccdb/cpp/src/tests> grep Test *.cc | grep include
test_MySQLProvider_Assignments.cc:#include "Tests/tests.h"
test_MySQLProvider_Assignments.cc:#include "Tests/catch.hpp"
test_MySQLProvider.cc:#include "Tests/catch.hpp"
test_MySQLProvider_Connection.cc:#include "Tests/catch.hpp"
test_MySQLProvider_Connection.cc:#include "Tests/tests.h"
test_MySQLProvider_Directories.cc:#include "Tests/catch.hpp"
test_MySQLProvider_Directories.cc:#include "Tests/tests.h"
test_MySQLProvider_RunRanges.cc:#include "Tests/catch.hpp"
test_MySQLProvider_RunRanges.cc:#include "Tests/tests.h"
test_MySQLProvider_TypeTables.cc:#include "Tests/catch.hpp"
test_MySQLProvider_TypeTables.cc:#include "Tests/tests.h"
test_MySQLProvider_Variations.cc:#include "Tests/catch.hpp"
test_MySQLProvider_Variations.cc:#include "Tests/tests.h"
test_MySqlUserAPI.cc:#include "Tests/catch.hpp"
test_MySqlUserAPI.cc:#include "Tests/tests.h"
test_SQLiteProvider_RunRanges.cc:#include "Tests/catch.hpp"
test_SQLiteProvider_RunRanges.cc:#include "Tests/tests.h"

**Comment by DraTeots** [comment]
Sorry, was on a conference. Will fix that now.

**Comment by sdobbs** [comment]
Just a quick bump on this - it looks like the last change needed to get v2 compiling for GlueX

**Comment by zihlmann** [comment]
this is still done fixed

**Comment by DraTeots** [comment]
This one is fixed as of couple days ago but I am still working on other issues.
